# Generated by Django 6.1.1 on 2026-09-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
