# Generated by Django 6.1.1 on 2026-09-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
