# Generated by Django 6.1.1 on 2026-09-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_customer_email_verified_customer_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
